//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectProfile.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry_Worked
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Industry_Worked()
        {
            this.Profile_Industry_Intermediate_Table = new HashSet<Profile_Industry_Intermediate_Table>();
        }
    
        public int Industry_id { get; set; }
        public string Industry_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile_Industry_Intermediate_Table> Profile_Industry_Intermediate_Table { get; set; }
    }
}
