//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectProfile.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile_table()
        {
            this.Profile_Industry_Intermediate_Table = new HashSet<Profile_Industry_Intermediate_Table>();
        }
    
        public System.Guid profile_id { get; set; }
        public string email_address { get; set; }
        public string greeting { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string postal_code { get; set; }
        public string primary_phone_Number { get; set; }
        public string Industry_worked { get; set; }
        public string resume_location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile_Industry_Intermediate_Table> Profile_Industry_Intermediate_Table { get; set; }
    }
}
