//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectProfile.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terms_Conditions
    {
        public int T_C_ID { get; set; }
        public string T_C_Description { get; set; }
        public bool IS_Checked { get; set; }
    }
}
